options {
    directory "/var/cache/bind";
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
    allow-query { any; };
    listen-on { any; };
    listen-on-v6 { any; };
    dnssec-validation no;
};

// Intercept all DNS resolutions globally and forward via our spoofed record zone mapping
zone "." IN {
    type master;
    file "/etc/bind/db.catchall";
};